import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
const root = path.resolve(import.meta.dirname, '..');
const read = name=>fs.readFileSync(path.join(root,name),'utf8');
const assets=JSON.parse(read('assets/manifest.json'));
for(const [name,file] of Object.entries(assets.characters)) assets.characters[name]=fs.readFileSync(path.join(root,'assets',file)).toString('base64');
assets.motion=JSON.parse(read(`assets/${assets.motion}`));
if(fs.existsSync(path.join(root,'assets/locomotion-source.json'))) assets.locomotion=JSON.parse(read('assets/locomotion-source.json'));
if(assets.environment) assets.environment=fs.readFileSync(path.join(root,'assets',assets.environment)).toString('base64');
for(const name of ['rain','snow']) if(fs.existsSync(path.join(root,`assets/${name}-motions.json`))) assets[`${name}Motion`]=JSON.parse(read(`assets/${name}-motions.json`));
if(assets.textures)for(const [name,file] of Object.entries(assets.textures))assets.textures[name]='data:image/jpeg;base64,'+fs.readFileSync(path.join(root,'assets',file)).toString('base64');
let html=read('src/template.html');
for(const [key,value] of Object.entries({ENGINE:read('vendor/engine.js')+read('vendor/hdr-loader.js'),ASSETS:`window.CLUB_ASSETS=${JSON.stringify(assets)};`,APP:read('src/app.js'),STYLE:read('src/style.css')})) html=html.replace(`{{${key}}}`,()=>value);
fs.writeFileSync(path.join(root,'index.html'),html);
if(process.argv.includes('--qa')) fs.writeFileSync(path.join(root,'qa.html'),html.replace('</body>',`<script>${read('tests/browser-fixture.js')}</script></body>`));
const sha256=crypto.createHash('sha256').update(html).digest('hex');
if(process.argv.includes('--baseline') && sha256!==JSON.parse(read('docs/recovery-provenance.json')).sha256) throw new Error('Baseline hash mismatch');
console.log(JSON.stringify({bytes:Buffer.byteLength(html),sha256,baseline:process.argv.includes('--baseline')},null,2));
